services:
  eternatus:
    build: .
    container_name: eternatus
    ports:
      - "80"
    restart: unless-stopped
    container_name: moisson-app
    volumes:
      - /Docker/config/eternatus:/usr/share/nginx/html
    networks: 
      - caddy_net
networks:
  caddy_net:
    external: true
  # Service optionnel pour un reverse proxy avec SSL
  # nginx-proxy:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx-proxy.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - moisson
