version: '3.8'

services:
  moisson:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: moisson-app
    
  # Service optionnel pour un reverse proxy avec SSL
  # nginx-proxy:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx-proxy.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - moisson